import Head from "next/head";
import Sidebar from "../components/Sidebar";
import React from "react";

export default function Home() {
  return (
    <div className="bg-black min-h-screen overflow-hidden">
      <Head>
        <title>Spotify 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Sidebar />
      </main>
      <div>player</div>
    </div>
  );
}
